spring:
  activemq:
    broker-url: tcp://192.168.0.101:61616 # activemq连接地址
    user: admin # 用户名
    password: admin # 密码
    send-timeout: 10000 # 发送超时时间
    pool:
      enabled: false # 是否创建 JmsPoolConnectionFactory 连接池
      idle-timeout: 30s # 空闲连接超时时间
      max-connections: 50 # 连接池中最大连接数
      max-sessions-per-connection: 100 # 每个连接最大会话